GET http://localhost:3000/songs

###

GET http://localhost:3000/songs/3

###
POST http://localhost:3000/songs
Content-Type: application/json

{
  "title": "Drink a Beer",
  "album": "Crash My Party",
  "artist": "Luke Bryan",
  "year": 2013
}

###
PATCH http://localhost:3000/songs/4.json
Content-Type: application/json

{
  "album": "Patrick Droney"
}

###
DELETE http://localhost:3000/songs/1